### PR TITLE
A dockerfile for mylar3

### PR DESCRIPTION
**Pull request by ajslater**
This Dockerfile works for x86-64.
I could make another for ARM or ARM64 easily as the python3.8 image comes in those flavors as well, but i'd need help testing it.

I don't know if you want a dockerfile in the root directory or in another repo but this PR seemed to be the easiest way to display it.
@evilhero @barbequesauce @claym
As always, comments welcome

### CODE REVIEW

**Comment by evilhero** [comment]
This looks fine to me, but I'm also not a docker user - so anyone else can chime in on this would be helpful. Otherwise, I'm ok with merging this into the root directory (try to keep it all together).

**Comment by claym** [comment]
failed on my ubuntu box

```
clay@hotpie:~/mylar3-docker$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

clay@hotpie:~/mylar3-docker$ uname -var
Linux hotpie 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux



clay@hotpie:~/mylar3-docker$ docker build -f ../mylar3/Dockerfile .
Sending build context to Docker daemon  2.607kB
Step 1/9 : FROM python:3.8
 ---> f88b2f81f83a
Step 2/9 : ARG MYLAR_COMMIT
 ---> Using cache
 ---> ff64d27c15d6
Step 3/9 : RUN echo "**** install system packages ****" &&  apt-get update &&  apt-get install -y --no-install-recommends     nodejs &&  echo "**** cleanup ****" &&  apt-get -y clean &&  rm -rf     /var/lib/apt/lists/*     /root/.cache     /tmp/*
 ---> Using cache
 ---> 2e4da932468e
Step 4/9 : RUN echo "**** install app ****" &&  git clone https://github.com/mylar3/mylar3.git --depth 1 --branch ${MYLAR_COMMIT:-python3-dev} --single-branch /app/mylar
 ---> Using cache
 ---> 7a40ff83e081
Step 5/9 : COPY root/ /
COPY failed: stat /var/lib/docker/tmp/docker-builder634991313/root: no such file or directory

```

**Comment by ajslater** [comment]
woops. extra config stuff left over from linuxserver i'm not using.
They run mylar as a service in the container instead of as a command (technically bad docker practice, but whatever, i do it all the time)
They also copy everything from /post-processing into $CONFIG_DIR/scripts/  every time the container starts.

**Comment by barbequesauce** [comment]
Why does it need node.js?

**Comment by ajslater** [comment]
https://pypi.org/project/cfscrape/ claims to need nodejs do to its magic

**Comment by barbequesauce** [comment]
No pressure @claym, but you're the best reviewer for this :)

**Comment by ajslater** [comment]
With the PyQT5 dependencies gone, move back to Alpine.
Uncompressed image size is now 380MB instead of 1.0GB.
Further space savings would be possible with a multi-step image build.

**Comment by claym** [comment]
Commit 47a9327364fa2c90b58943dcb06ff361ef09f68c built and ran successfully. I didn't grab any comics or anything, but it started up correctly.

**Comment by evilhero** [comment]
Can you do a PR against the current python3-dev branch so that the python3-dev merges aren't showing up in there please ? Otherwise, @claym  tested it ok - so I'm ok with merging it once the above aspect is taken care of.

**Comment by ajslater** [comment]
Eh. I'll just make a new PR.

**Pull request closed without merging**
