### PR TITLE
Cleanup search file

### PR DESCRIPTION
**Pull request by kalinon**
While trying to parse and look through the `search.py` for fixes and random errors over the last few weeks, ive noticed a large number of "warnings" in PyCharm. So in an attempt to help cleanup this file i have gone through and corrected some of the smaller issues. But due to the sheer number of small things, it leads to a larger changeset. This includes #475 and #474 .

I have tried to keep each commit in this PR down to a specific warning/error so all the changes are not jumbled into one giant commit. So if you check each commit, it will give you a smaller chunk of specific changes.

Pre changes:
Screen Shot 2020-10-01 at 6 24 17 PM

Post changes:
Screen Shot 2020-10-01 at 6 23 15 PM

### CODE REVIEW

**Comment by evilhero** [comment]
This is also done all against the master branch - which we will never merge a PR directly into unless it's something critical in nature (as then it screws up the git process).

If you can, can you resubmit this against the dev branch - or if you don't want to (or it's too much work) you can leave this PR as is and myself and / or @barbequesauce can work through them as one-offs, basically cherry-picking the non-breaking items (which granted there are alot).

If you do resubmit against the dev branch - we need them to be done in smaller chunks instead of having one large PR. When you have a PR of this size it's really daunting to go through line by line to see what the changes are - and we have to do that due to the sheer size of the changes. 

It makes it next to impossible to get a clean PR done against as there's always something different happening. If you can isolate them or group them by something, it will make the approval process much quicker on our part (plus if any changes get pushed to search.py prior to this actually get merged, you'd have to rebase or redo the entire PR depending on the number of sweeping changes done).

Aside from all of that, this was a huge PR to do and much respect for taking the time and effort to put it together to bring to our attention 👍

**Comment by kalinon** [comment]
Yeah i keep forgetting to make it merge into dev. its branched off there.

**Comment by kalinon** [comment]
I understand, i knew it was a huge PR. I tried to group the commits, but its hard when you then need each PR to be merged before the next, etc etc. So i tried to keep the commits into track-able chunks as you describe.

**Comment by kalinon** [comment]
Just an update. I've been running these changes and have seen some improvement with searching and matching. I no longer need to restart the service to get a new search running and am seeing matches occur frequently.

**Comment by evilhero** [comment]
Yep, most of these seem ok tbh.

One of the main reasons I haven't pushed any changes yet is because of the 2 main search loops within search.py.  I redid these on my local repo which is almost identical to your changes (and have for awhile now, before your PR even lol), but it adds in exception logging into the GUI on it's own popup so you can view the exception, traceback, etc, and even a log snippet leading up to the exception (yes, trying to make things simpler for issues) all from within a popup.

I pushed some simple fixes from this PR in #495 that involved __init__.py.  I'm preparing for my exception/search one to go up next, so I have/will be cherry-picking from your PR and adding into there to save some time. It's not going to make it any easier going thru and seeing what this particular PR exactly fixes, but at least I can address hopefully most of the problematic ones in the next PR.

**Comment by evilhero** [comment]
Closing this as search.py has since gone thru both black + flake8. 

If there are still problems, we'll take it from a clean slate ;)

Thanks for bringing this to light!

**Pull request closed without merging**
