### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by sukhysall**
First attempt at the dark mode theme "carbon".

### CODE REVIEW

**Comment by sukhysall** [comment]
@evilhero 
@barbequesauce 

Is it normal to be a little giddy with your first pull request?

**Comment by barbequesauce** [comment]
Yep, definitely.

Rebasing/merging this to the dark-theme branch only then applying locally, will comment back with findings.

Thank you!

**Comment by barbequesauce** [comment]
Overall - solid work here. Nice job and thanks for the contribution.

Some feedback:
- comic details page color coding is missing (https://shrimpandgrits.net/linx/77s4oqaq.png)
- LOVE this choice (https://shrimpandgrits.net/linx/43zikqg6.png)
- Not sure what happened at the start of the alphaindex (https://shrimpandgrits.net/linx/pqmok8ap.png)
- Wanted screen has a few things - first, checkboxes are not aligned (this might be an issue with default too, honestly); the icon needs work; bold choice of color for wanted (https://shrimpandgrits.net/linx/fhwvnpki.png)
- Pulllist (This Week) - auto-want text color needs tweaking (https://shrimpandgrits.net/linx/5unckzhy.png)
- Toast notifications are unreadable (I couldn't grab a screenshot of this)
- History page color choices need better contrast (https://shrimpandgrits.net/linx/5oynrg10.png)

Looking forward to seeing your next rev!

**Comment by sukhysall** [comment]
@barbequesauce thanks for the feedback. Very helpful. PS. This is my first attempt at modifying code, literally my first attempt. It's quite fun when work isn't getting in the way.

Some of the stuff is easily remedied (My Mylar 2 code addressed this but looks like I missed something in Mylar 3)

Alphaindex is a tricky beast. can't quite pinpoint where exactly the change needs to be but I'm already aware of that so will look further

Checkbox alignment is a new one for me so will experiement with that.

toast notifications is one I thought I had modified correctly. They're referenced as Ajax messages and they are a tricky beast lol. I'll sort them.

History page was clearly missed as I was modifying a barebones Mylar. I will test my changes on my working Mylar copy then apply to the dev Mylar copy which I push up.

**Comment by BRTPOB** [comment]
Just ignore alphaindex, it was written by a dirty mac user.

**Comment by sukhysall** [comment]
@BRTPOB :)  :)  :)

It's just a colour change from what is currently unreadable dark to what will become a Yellow variant against the dark background

**Comment by barbequesauce** [comment]
OI @BRTPOB STUFF IT

**Comment by barbequesauce** [comment]
@sukhysall note the html file change in #293, that needs to be updated here too please

**Comment by sukhysall** [comment]
@barbequesauce Copy that. Apologies for delay in fixing, My spare time has now been occupied by arrival of kids and (all the subsequent home schooling required during this lockdown)

But it's holidays next week :) :) :)

**Comment by barbequesauce** [comment]
You might want to join us in IRC - we're all on and off sporadically but the real development discussion happens there...

**Pull request merged**
