### PR TITLE
[FIX] platform independent devnull location + bug in sending covers to Telegram

### PR DESCRIPTION
**Pull request by Bart274**
Without this fix, the git version check fails on Windows

### CODE REVIEW

**Comment by barbequesauce** [comment]
TIL os.devnull was a thing.

**Comment by Bart274** [comment]
@barbequesauce I didn’t knew it either until I started looking into the issue I had to run the py3 version and saw it was already used in this project here: https://github.com/mylar3/mylar3/blob/05652beef1172b58f98624c8ea34d52d4f881c12/Mylar.py#L34

**Comment by Bart274** [comment]
@evilhero this also fixes sending covers to Telegram which was broken since you changed the code to the extracted covers. I'll make branches in the future to prevent PR's for multiple fixes

**Comment by evilhero** [comment]
All good in development (haven't tested telegram obviously)! Cheers!

**Pull request merged**
