### PR TITLE
catches error raised by post processing

### PR DESCRIPTION
**Pull request by kalinon**
Get this error sometimes when running post processing. It halts all post processing.

```
 20-Aug-2020 15:03:09 - ERROR :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
   File "/app/mylar/mylar/logger.py", line 337, in new_run
     old_run(*args, **kwargs)
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/app/mylar/mylar/PostProcessor.py", line 711, in Process
     updater.dbUpdate([cs['ComicID']])
   File "/app/mylar/mylar/updater.py", line 187, in dbUpdate
     chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
   File "/app/mylar/mylar/importer.py", line 106, in addComictoDB
     comic = cv.getComic(comicid, 'comic')
   File "/app/mylar/mylar/cv.py", line 160, in getComic
     return GetComicInfo(comicid, dom)
   File "/app/mylar/mylar/cv.py", line 227, in GetComicInfo
     tracks = dom.getElementsByTagName('issue')
 AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'

 Traceback (most recent call last):
   File "/app/mylar/mylar/logger.py", line 337, in new_run
     old_run(*args, **kwargs)
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/app/mylar/mylar/PostProcessor.py", line 711, in Process
     updater.dbUpdate([cs['ComicID']])
   File "/app/mylar/mylar/updater.py", line 187, in dbUpdate
     chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
   File "/app/mylar/mylar/importer.py", line 106, in addComictoDB
     comic = cv.getComic(comicid, 'comic')
   File "/app/mylar/mylar/cv.py", line 160, in getComic
     return GetComicInfo(comicid, dom)
   File "/app/mylar/mylar/cv.py", line 227, in GetComicInfo
     tracks = dom.getElementsByTagName('issue')
 AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
```

```
 20-Aug-2020 15:23:17 - WARNING :: mylar.pulldetails.82 : Thread-13 : Error fetching data from ComicVine: HTTPSConnectionPool(host='comicvine.gamespot.com', port=443):
 20-Aug-2020 15:23:17 - ERROR :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
   File "/app/mylar/mylar/logger.py", line 337, in new_run
     old_run(*args, **kwargs)
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/app/mylar/mylar/PostProcessor.py", line 711, in Process
     updater.dbUpdate([cs['ComicID']])
   File "/app/mylar/mylar/updater.py", line 187, in dbUpdate
     chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
   File "/app/mylar/mylar/importer.py", line 106, in addComictoDB
     comic = cv.getComic(comicid, 'comic')
   File "/app/mylar/mylar/cv.py", line 160, in getComic
     return GetComicInfo(comicid, dom)
   File "/app/mylar/mylar/cv.py", line 227, in GetComicInfo
     tracks = dom.getElementsByTagName('issue')
 AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'

 Traceback (most recent call last):
   File "/app/mylar/mylar/logger.py", line 337, in new_run
     old_run(*args, **kwargs)
   File "/usr/local/lib/python3.8/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/app/mylar/mylar/PostProcessor.py", line 711, in Process
     updater.dbUpdate([cs['ComicID']])
   File "/app/mylar/mylar/updater.py", line 187, in dbUpdate
     chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
   File "/app/mylar/mylar/importer.py", line 106, in addComictoDB
     comic = cv.getComic(comicid, 'comic')
   File "/app/mylar/mylar/cv.py", line 160, in getComic
     return GetComicInfo(comicid, dom)
   File "/app/mylar/mylar/cv.py", line 227, in GetComicInfo
     tracks = dom.getElementsByTagName('issue')
 AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
```

### CODE REVIEW

**Comment by evilhero** [comment]
Firstly, thanks for the PR! 

The pro Lem from that traceback seems to point to a CV related issue - them being down on not responding properly.

I'm curious now, can you provide the debug log leading up to that error? 

I'm curious as to how it's getting triggered as it would occur in more than the one module if it is via CV.  Meaning if it is via CV it might be better handled in a different module, but still have the same results as this PR.

Also, you if the PR stands you need to do it against the python3-dev branch, not master.

**Comment by kalinon** [comment]
> Firstly, thanks for the PR!
> 
> The pro Lem from that traceback seems to point to a CV related issue - them being down on not responding properly.
> 
> I'm curious now, can you provide the debug log leading up to that error?
> 
> I'm curious as to how it's getting triggered as it would occur in more than the one module if it is via CV. Meaning if it is via CV it might be better handled in a different module, but still have the same results as this PR.
> 
> Also, you if the PR stands you need to do it against the python3-dev branch, not master.

Yeah its a CV issue. if a timeout or whatever happens it breaks the whole post processing. Discovered it while having internet issues :D ill try to find the surrounding logs and fix the target branch

**Comment by kalinon** [comment]
Heres some log output:

```
bash-5.0# grep mylar.excepthook.315 ./mylar.log* -B 15 -A 15
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.parseit.1175 : SEARCH-QUEUE : series title possibly: 2020.08
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1141 : SEARCH-QUEUE : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': '2020.08.12 Weekly Pack', 'comiclocation': None, 'series_name': '2020.08', 'series_name_decoded': '2020.08', 'issueid': None, 'dynamic_name': '202008', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': None, 'issue_number': '.12', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
./mylar.log.4-20-Aug-2020 16:15:08 - INFO    :: mylar.NZB_SEARCH.1142 : SEARCH-QUEUE : booktype: Digital / parsed_booktype: issue [ignore_booktype: False]
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1156 : SEARCH-QUEUE : Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.868 : SEARCH-QUEUE : checking search result: 2020.08.05 Weekly Pack
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.878 : SEARCH-QUEUE : sub: 2020.08.05 Weekly Pack
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.927 : SEARCH-QUEUE : comsize_b: 3650722201
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.964 : SEARCH-QUEUE : size given as: 3.4 GB
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1014 : SEARCH-QUEUE : store date used is : 2020-08-12
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1015 : SEARCH-QUEUE : date used is : 2020-08-12
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1058 : SEARCH-QUEUE : usedate: 2020-08-12
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1100 : SEARCH-QUEUE : [CONV] pubdate: 2020-08-05  < storedate: 2020-08-11
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.1101 : SEARCH-QUEUE : Wed, 05 Aug 2020 00:00:00 is before store date of 2020-08-12. Ignoring search result as this is not the right issue.
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.868 : SEARCH-QUEUE : checking search result: 2020.07.29 Weekly Pack
./mylar.log.4-20-Aug-2020 16:15:08 - DEBUG   :: mylar.NZB_SEARCH.878 : SEARCH-QUEUE : sub: 2020.07.29 Weekly Pack
./mylar.log.4:20-Aug-2020 16:15:08 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
./mylar.log.4-  File "/app/mylar/mylar/search.py", line 922, in NZB_SEARCH
./mylar.log.4-    comsize_b = helpers.human2bytes(entry['size'])
./mylar.log.4-  File "/app/mylar/mylar/helpers.py", line 189, in human2bytes
./mylar.log.4-    assert float(num) and letter in symbols
./mylar.log.4-ValueError: could not convert string to float: '2.7G/1.04'
./mylar.log.4-
./mylar.log.4-During handling of the above exception, another exception occurred:
./mylar.log.4-
./mylar.log.4-Traceback (most recent call last):
./mylar.log.4-  File "/app/mylar/mylar/logger.py", line 337, in new_run
./mylar.log.4-    old_run(*args, **kwargs)
./mylar.log.4-  File "/usr/local/lib/python3.8/threading.py", line 870, in run
./mylar.log.4-    self._target(*self._args, **self._kwargs)
./mylar.log.4-  File "/app/mylar/mylar/helpers.py", line 3145, in search_queue
./mylar.log.4-    ss_queue = mylar.search.searchforissue(item['issueid'])
--
./mylar.log.5-20-Aug-2020 15:23:10 - INFO    :: mylar.Process.564 : Thread-13 : Now checking: The Amazing Spider-Man [85076]
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.Process.696 : Thread-13 : [POST-PROCESSING] No corresponding issue #795 found for 112161
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.Process.709 : Thread-13 : [POST-PROCESSING] The Amazing Spider-Man [112161] Was refreshed less than 1 hours ago. Skipping Refresh at this time so we don't hammer things unnecessarily.
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.Process.696 : Thread-13 : [POST-PROCESSING] No corresponding issue #795 found for 2127
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.Process.709 : Thread-13 : [POST-PROCESSING] The Amazing Spider-Man [2127] Was refreshed less than 1 hours ago. Skipping Refresh at this time so we don't hammer things unnecessarily.
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.Process.696 : Thread-13 : [POST-PROCESSING] No corresponding issue #795 found for 73420
./mylar.log.5-20-Aug-2020 15:23:10 - INFO    :: mylar.dbUpdate.79 : Thread-13 : Starting update for 1 active comics
./mylar.log.5-20-Aug-2020 15:23:10 - INFO    :: mylar.dbUpdate.121 : Thread-13 : Refreshing/Updating: The Amazing Spider-Man (2014) [73420]
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.dbUpdate.140 : Thread-13 : CV_OneTimer option enabled...
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.dbUpdate.142 : Thread-13 : Gathering the status of all issues for the series.
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.dbUpdate.152 : Thread-13 : Checking how out of whack the series is.
./mylar.log.5-20-Aug-2020 15:23:10 - DEBUG   :: mylar.dbUpdate.184 : Thread-13 : Refreshing the series and pulling in new data using only CV.
./mylar.log.5-20-Aug-2020 15:23:10 - INFO    :: mylar.addComictoDB.86 : Thread-13 : aliases currently: None
./mylar.log.5-20-Aug-2020 15:23:10 - INFO    :: mylar.validateAndCreateDirectory.1717 : Thread-13 : [DIRECTORY-CHECK] Found comic directory: /comics/Marvel/The Amazing Spider-Man (2014)
./mylar.log.5-20-Aug-2020 15:23:17 - WARNING :: mylar.pulldetails.82 : Thread-13 : Error fetching data from ComicVine: HTTPSConnectionPool(host='comicvine.gamespot.com', port=443): Max retries exceeded with url: /api/volume/4050-73420/?api_key=18357f40df87fb4a4bb6f5bb27cd8ad1deb08d3e&format=xml&field_list=name,count_of_issues,issues,start_year,site_detail_url,image,publisher,description,first_issue,deck,aliases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fec1c23dd30>: Failed to establish a new connection: [Errno -3] Try again'))
./mylar.log.5:20-Aug-2020 15:23:17 - ERROR   :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
./mylar.log.5-  File "/app/mylar/mylar/logger.py", line 337, in new_run
./mylar.log.5-    old_run(*args, **kwargs)
./mylar.log.5-  File "/usr/local/lib/python3.8/threading.py", line 870, in run
./mylar.log.5-    self._target(*self._args, **self._kwargs)
./mylar.log.5-  File "/app/mylar/mylar/PostProcessor.py", line 711, in Process
./mylar.log.5-    updater.dbUpdate([cs['ComicID']])
./mylar.log.5-  File "/app/mylar/mylar/updater.py", line 187, in dbUpdate
./mylar.log.5-    chkstatus = mylar.importer.addComictoDB(ComicID, mismatch, calledfrom='dbupdate', annload=annload, csyear=csyear, fixed_type=fixed_type)
./mylar.log.5-  File "/app/mylar/mylar/importer.py", line 106, in addComictoDB
./mylar.log.5-    comic = cv.getComic(comicid, 'comic')
./mylar.log.5-  File "/app/mylar/mylar/cv.py", line 160, in getComic
./mylar.log.5-    return GetComicInfo(comicid, dom)
./mylar.log.5-  File "/app/mylar/mylar/cv.py", line 227, in GetComicInfo
./mylar.log.5-    tracks = dom.getElementsByTagName('issue')
./mylar.log.5-AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
--
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.parseit.1175 : SEARCH-QUEUE : series title possibly: 2020.08
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1140 : SEARCH-QUEUE : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': '2020.08.12 Weekly Pack', 'comiclocation': None, 'series_name': '2020.08', 'series_name_decoded': '2020.08', 'issueid': None, 'dynamic_name': '202008', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': None, 'issue_number': '.12', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
./mylar.log.5-20-Aug-2020 16:09:28 - INFO    :: mylar.NZB_SEARCH.1141 : SEARCH-QUEUE : booktype: Digital / parsed_booktype: issue [ignore_booktype: False]
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1155 : SEARCH-QUEUE : Booktypes do not match. Looking for Digital, this is a issue. Ignoring this result.
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : checking search result: 2020.08.05 Weekly Pack
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.877 : SEARCH-QUEUE : sub: 2020.08.05 Weekly Pack
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.926 : SEARCH-QUEUE : comsize_b: 3650722201
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.963 : SEARCH-QUEUE : size given as: 3.4 GB
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1013 : SEARCH-QUEUE : store date used is : 2020-08-12
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1014 : SEARCH-QUEUE : date used is : 2020-08-12
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1057 : SEARCH-QUEUE : usedate: 2020-08-12
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1099 : SEARCH-QUEUE : [CONV] pubdate: 2020-08-05  < storedate: 2020-08-11
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.1100 : SEARCH-QUEUE : Wed, 05 Aug 2020 00:00:00 is before store date of 2020-08-12. Ignoring search result as this is not the right issue.
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : checking search result: 2020.07.29 Weekly Pack
./mylar.log.5-20-Aug-2020 16:09:28 - DEBUG   :: mylar.NZB_SEARCH.877 : SEARCH-QUEUE : sub: 2020.07.29 Weekly Pack
./mylar.log.5:20-Aug-2020 16:09:28 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
./mylar.log.5-  File "/app/mylar/mylar/search.py", line 921, in NZB_SEARCH
./mylar.log.5-    comsize_b = helpers.human2bytes(entry['size'])
./mylar.log.5-  File "/app/mylar/mylar/helpers.py", line 189, in human2bytes
./mylar.log.5-    assert float(num) and letter in symbols
./mylar.log.5-ValueError: could not convert string to float: '2.7G/1.04'
./mylar.log.5-
./mylar.log.5-During handling of the above exception, another exception occurred:
./mylar.log.5-
./mylar.log.5-Traceback (most recent call last):
./mylar.log.5-  File "/app/mylar/mylar/logger.py", line 337, in new_run
./mylar.log.5-    old_run(*args, **kwargs)
./mylar.log.5-  File "/usr/local/lib/python3.8/threading.py", line 870, in run
./mylar.log.5-    self._target(*self._args, **self._kwargs)
./mylar.log.5-  File "/app/mylar/mylar/helpers.py", line 3145, in search_queue
./mylar.log.5-    ss_queue = mylar.search.searchforissue(item['issueid'])
```

**Comment by barbequesauce** [comment]
The branch change didnt clean up the commit history - I resubmitted as #430 as a direct patch. Thank you for the work!

**Pull request closed without merging**
