### PR TITLE
Fix datatables error on ImportResults 

### PR DESCRIPTION
**Pull request by eroth312**
error due to extra, out-of-place table rows.  solution was found here: https://www.datatables.net/forums/discussion/comment/112718/

error causes datatables to not load, which prevents any of the useful features for sorting, paging, etc.

js console error

### CODE REVIEW

**Comment by eroth312** [comment]
yeah - for sure, not sure how my db stuff snuck in here.   didn't intend that PR to come through yet.

**Comment by eroth312** [comment]
@barbequesauce - should be cleaned up now. 
I'll send the other one through once this is approved to be sure nothing else is broken.

**Comment by barbequesauce** [comment]
YEah, the commit history will still be messed up. Would you mind killing this PR and starting a new one for this commit please?

**Comment by eroth312** [comment]
sure thing - on it.

**Comment by barbequesauce** [comment]
Thanks...

**Pull request closed without merging**
